/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as extensions from "./extensions";
export { Governor__factory } from "./Governor__factory";
export { IGovernor__factory } from "./IGovernor__factory";
