/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cardSol from "./Card.sol";
export type { cardSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as test from "./test";
export type { test };
export type { CardsAgainstHumanity } from "./CardsAgainstHumanity";
export type { CardsGovernor } from "./CardsGovernor";
