/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface MockEntropyInterface extends utils.Interface {
  functions: {
    "feeInWei()": FunctionFragment;
    "getFee(address)": FunctionFragment;
    "request(address,bytes32,bool)": FunctionFragment;
    "reveal(address,uint64,bytes32,bytes32)": FunctionFragment;
    "sequenceNumberCounter()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "feeInWei"
      | "getFee"
      | "request"
      | "reveal"
      | "sequenceNumberCounter"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "feeInWei", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getFee",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "request",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "reveal",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sequenceNumberCounter",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "feeInWei", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "request", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reveal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sequenceNumberCounter",
    data: BytesLike
  ): Result;

  events: {};
}

export interface MockEntropy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockEntropyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    feeInWei(overrides?: CallOverrides): Promise<[BigNumber]>;

    getFee(
      provider: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { feeAmount: BigNumber }>;

    request(
      provider: PromiseOrValue<string>,
      userCommitment: PromiseOrValue<BytesLike>,
      useBlockHash: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    reveal(
      provider: PromiseOrValue<string>,
      sequenceNumber: PromiseOrValue<BigNumberish>,
      userRandomness: PromiseOrValue<BytesLike>,
      providerRevelation: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sequenceNumberCounter(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  feeInWei(overrides?: CallOverrides): Promise<BigNumber>;

  getFee(
    provider: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  request(
    provider: PromiseOrValue<string>,
    userCommitment: PromiseOrValue<BytesLike>,
    useBlockHash: PromiseOrValue<boolean>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  reveal(
    provider: PromiseOrValue<string>,
    sequenceNumber: PromiseOrValue<BigNumberish>,
    userRandomness: PromiseOrValue<BytesLike>,
    providerRevelation: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sequenceNumberCounter(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    feeInWei(overrides?: CallOverrides): Promise<BigNumber>;

    getFee(
      provider: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    request(
      provider: PromiseOrValue<string>,
      userCommitment: PromiseOrValue<BytesLike>,
      useBlockHash: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    reveal(
      provider: PromiseOrValue<string>,
      sequenceNumber: PromiseOrValue<BigNumberish>,
      userRandomness: PromiseOrValue<BytesLike>,
      providerRevelation: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    sequenceNumberCounter(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    feeInWei(overrides?: CallOverrides): Promise<BigNumber>;

    getFee(
      provider: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    request(
      provider: PromiseOrValue<string>,
      userCommitment: PromiseOrValue<BytesLike>,
      useBlockHash: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    reveal(
      provider: PromiseOrValue<string>,
      sequenceNumber: PromiseOrValue<BigNumberish>,
      userRandomness: PromiseOrValue<BytesLike>,
      providerRevelation: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sequenceNumberCounter(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    feeInWei(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFee(
      provider: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    request(
      provider: PromiseOrValue<string>,
      userCommitment: PromiseOrValue<BytesLike>,
      useBlockHash: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    reveal(
      provider: PromiseOrValue<string>,
      sequenceNumber: PromiseOrValue<BigNumberish>,
      userRandomness: PromiseOrValue<BytesLike>,
      providerRevelation: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sequenceNumberCounter(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
