/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extensions from "./extensions";
export type { extensions };
export type { Governor } from "./Governor";
export type { IGovernor } from "./IGovernor";
