/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGameCollection,
  IGameCollectionInterface,
} from "../../../contracts/interfaces/IGameCollection";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "data",
        type: "string",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IGameCollection__factory {
  static readonly abi = _abi;
  static createInterface(): IGameCollectionInterface {
    return new utils.Interface(_abi) as IGameCollectionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGameCollection {
    return new Contract(address, _abi, signerOrProvider) as IGameCollection;
  }
}
