/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IGame__factory } from "./IGame__factory";
export { IGameCollection__factory } from "./IGameCollection__factory";
