/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockEntropySol from "./MockEntropy.sol";
export type { mockEntropySol };
export type { MockCollection } from "./MockCollection";
export type { MockGame } from "./MockGame";
