/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace IGame {
  export type UserStatsStruct = {
    games: PromiseOrValue<BigNumberish>;
    winner: PromiseOrValue<BigNumberish>;
  };

  export type UserStatsStructOutput = [BigNumber, BigNumber] & {
    games: BigNumber;
    winner: BigNumber;
  };
}

export interface IGameInterface extends utils.Interface {
  functions: {
    "userStats(address)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "userStats"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "userStats",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "userStats", data: BytesLike): Result;

  events: {};
}

export interface IGame extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IGameInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    userStats(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[IGame.UserStatsStructOutput]>;
  };

  userStats(
    user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<IGame.UserStatsStructOutput>;

  callStatic: {
    userStats(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<IGame.UserStatsStructOutput>;
  };

  filters: {};

  estimateGas: {
    userStats(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    userStats(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
